* Simple Emacs flake

a simple emacs flake using [[https://github.com/nix-community/emacs-overlay][emacs-overlay]]

Has three packages:
- Emacs with the extra packages and config wrapped together (I don't use this anymore)
- Emacs with just the extra packages and PATH binaries wrapped
- Emacs with packages for exwm
  
** Adding/editing config files 
- You can place ~*.el~ files in =./config=.
- Or, you can use your own config independent of this flake.
- If you use =./config=: Nix will read the directory in lexicographical order, concatenate the contents of each config, and write all of that to an init file.
  - So, to edit load order of config files, edit the names of the files when necessary.
  - For example, my init file is named ~00-init.el~.

** Adding emacs packages
- Packages are added by adding them in epkgs.nix.
  - Ex.
    #+begin_src nix
      epkgs: with epkgs; [
        ### Add your emacs packages here ###
        treesit-grammars.with-all-grammars
        ...
      ];
    #+end_src
    
- You can add packages traditionally in your elisp files as well.
  - If you declare your packages traditionally in the =./config= directory, Nix will parse the elisp in ./config and get any packages found from Nixpkgs instead.
  - Ex. use-package declarations in =./config= will fetch packages from Nixpkgs instead of MELPA if ~:ensure t~ is set.
** Adding external packages to emacs's path
If you need any extra, non-emacs packages, you can add them to your emacs's path by editing ./wrappers.nix:
#+BEGIN_SRC nix
  emacs-wrapped = with pkgs; symlinkJoin {
    name = "emacs";
    buildInputs = [ makeWrapper ];
    paths = [ emacs-unwrapped ];
    postBuild = let 
    path = [
      ## Add your external packages here ##
      fzf
      ripgrep
      ...
    ];
    ...
  };
#+END_SRC

** Notes and quirks
- You should probably not use the config I have here. It isn't plug-n-play, is just patchwerk of other configs, and I don't use it anymore anyways. Honestly, I don't even want to look at the elisp. It is just left here as an example.

** Credits
- Parts of the configs were taken from [[https://git.sr.ht/~ashton314/emacs-bedrock][emacs-bedrock]], and the System Crafters Emacs From Scratch video series helped a lot.
