;; Set fonts for emacs
(set-face-attribute 'default nil :font "lemon" :height 150)
(set-face-attribute 'tooltip nil :font "lemon" :height 150)

(add-to-list 'default-frame-alist '(font . "lemon"))
(set-fontset-font t 'unicode (font-spec :name "lemon") nil)
;; (set-fontset-font t 'unicode (font-spec :name "Noto Color Emoji") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "CozetteHiDpi") nil 'append)
;; (set-fontset-font t 'unicode (font-spec :name "JetBrainsMono") nil 'append)
;; (set-fontset-font t 'unicode (font-spec :name "DejaVu Sans Mono") nil 'append)
(set-frame-font "lemon" nil t)
;; Set the variable pitch face
(set-face-attribute 'variable-pitch nil :font "Terminus" :height 160 :weight 'regular)
;; CJK fonts
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_tr") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_tw") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced ja") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced ko") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_hk") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_cn") nil 'append)

(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_tr") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_tw") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced ja") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced ko") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_hk") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_cn") nil 'append)

(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_tr") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_tw") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced ja") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced ko") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_hk") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_cn") nil 'append)

;; (set-fontset-font t 'unicode (font-spec :name "WenQuanYi Bitmap Song") nil 'append)
;; (set-fontset-font t 'unicode (font-spec :name "WenQuanYi Bitmap Song") nil 'append)
;; (set-fontset-font t 'unicode (font-spec :name "WenQuanYi Bitmap Song") nil 'append)
;; (set-fontset-font t 'han (font-spec :name "WenQuanYi Bitmap Song") nil)
;; (set-fontset-font t 'kana (font-spec :name "WenQuanYi Bitmap Song") nil)
;; (set-fontset-font t 'hangul (font-spec :name "WenQuanYi Bitmap Song") nil)


(defun set-fonts-for-emacsclient ()
  (add-to-list 'default-frame-alist '(font . "lemon"))
  (set-fontset-font t 'unicode (font-spec :name "lemon") nil)
  (set-fontset-font t 'unicode (font-spec :name "Noto Color Emoji") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "CozetteHiDpi") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "JetBrainsMono") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "DejaVu Sans Mono") nil 'append)
  (set-frame-font "lemon" nil t)
  ;; Set the variable pitch face
  (set-face-attribute 'variable-pitch nil :font "Terminus" :height 160 :weight 'regular)
  ;; CJK fonts
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_tr") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_tw") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced ja") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced ko") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_hk") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 10px Monospaced zh_cn") nil 'append)

  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_tr") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_tw") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced ja") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced ko") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_hk") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 12px Monospaced zh_cn") nil 'append)

  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_tr") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_tw") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced ja") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced ko") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_hk") nil 'append)
  (set-fontset-font t 'unicode (font-spec :name "Ark Pixel 16px Monospaced zh_cn") nil 'append))

(add-hook 'server-after-make-frame-hook 'set-fonts-for-emacsclient)
